apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angular-deployment 
spec: 
  selector: 
    matchLabels: 
      app: angular 
        
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels:  kubectl get services
        app: angular 
    spec: 
      containers: 
      - name: angular 
        image: arifur4321/stringappn:v1 
        ports: 
        - containerPort: 8090
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angular-service 
spec: 
  selector: 
    app: angular 
     
  ports: 
  - protocol: TCP 
    port: 8090
    targetPort: 8090
    nodePort: 31000 
  type: NodePort 